#!/usr/bin/expect -f

spawn "netExtender" --username $env(VPN_USER) --password $env(VPN_PASS) --domain $env(VPN_DOMAIN) --ppp-sync --auto-reconnect $env(VPN_SERVER)

set timeout 5

expect -exact "Do you want to proceed? (Y:Yes, N:No, V:View Certificate)" {
  send -- "Y\n"
}

# Expect tunnel to actually start
expect {
  "NetExtender connected successfully." {
  } timeout {
    send_user -- "Failed to bring tunnel up after 5"
    exit 1
  }
}

# Expect tunnel to stop but not exit
set timeout -1
expect {
  "Exiting NetExtender client" {
    send_user -- "EXIT CLIENT"
    exit 1
  }
  eof {
    send_user -- "EXIT"
    exit
  }
}
